#! /bin/sh

#launch sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

#launch polybar
bash $HOME/.config/polybar/launch.sh

#set desktops
bspc monitor -d I II III IV V VI VII VIII

#window settings
bspc config border_width         6
bspc config window_gap           10

bspc config split_ratio          0.55
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# colors
source ~/.config/bspwm/theme

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

#window rules
bspc rule -a Nitrogen state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Thunar desktop='^5' follow=on
