#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bash $HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         6
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# colors

bspc config focused_border_color \#dfbf8e
bspc config normal_border_color  \#665c54 

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc rule -a Nitrogen state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Thunar desktop='^5' follow=on
